baseURL: "https://bizinvoke.github.io/home/"
theme: "bizInvoke"
languageCode: "en-us"
publishDir: "docs"

title: "BizInvoke"

hasCJKLanguage: true
enableInlineShortcodes: true
enableEmoji: true
markup:
  goldmark:
    renderer:
      unsafe: true

# googleAnalytics: ""

summaryLength: 20

params:
  title: "株式会社BizInvoke"
  description: "私たちは、多くのデザイナーや開発者が揃った専門のエンジニアチームです。もし私たちのサービスが必要なプロジェクトがありましたら、お気軽にご連絡ください。私たちは喜んでお手伝いいたします。"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    dribbble: "#"
    instagram: "#"
    facebook: "#"
    twitter: "#"

  location:
    - "〒247-0056 神奈川県鎌倉市 大船６丁目１２ー１５"

  contact:
    - "info@bizinvoke.com"
    - "神奈川, 日本"

  copyright: "© 2023 BizInvoke, Inc."

menus:
  main:
    - name: "ホーム"
      url: "/#hero"
      weight: 1

    - name: "当社について"
      url: "/#portfolio"
      weight: 2

    - name: "サービス"
      url: "/#services"
      weight: 3

    - name: "会社情報"
      url: "/#"
      weight: 4

    - name: "ブログ"
      url: "/blog"
      weight: 5

  buttons:
    - name: "お問合わせ"
      url: "/#"
      weight: 5
      pre: "btn btn-primary text-light"

  footer:
    - name: "ホーム"
      url: "/#hero"
      weight: 1

    - name: "当社について"
      url: "/#portfolio"
      weight: 2

    - name: "サービス"
      url: "/#services"
      weight: 3

    - name: "会社情報"
      url: "/#"
      weight: 4

    - name: "ブログ"
      url: "/blog"
      weight: 5

taxonomies:
  series: "series"
  tags: "tags"
